name: Build and Commit JAR

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn -q -DskipTests package

      - name: Copy JAR to release/
        run: |
          mkdir -p release
          cp target/*-1.0.0.jar release/bfh-java-qualifier-1.0.0.jar

      - name: Commit JAR back to repo
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add release/bfh-java-qualifier-1.0.0.jar
          git commit -m "CI: add compiled JAR [skip ci]" || echo "No changes to commit"
          git push
